### ISSUE TITLE
Upgrade CI for Instagram Challenge

### ISSUE THREAD

**Issue by tansaku** [makersacademy/instagram-challenge#97]
Rubocop config on instagram- challenge needs update to avoid many 100s of little corrections

Needs to be completed before coming Friday (16th)

**Comment by tansaku** [comment]
planning to pair with @ptolemybarnes on this

**Comment by tansaku** [comment]
other senior coaches most welcome

**Comment by tansaku** [comment]
@ptolemy thanks for joining me for that - did another test with another previous student - rails/ruby hound all quietened down, but rubocop javascript defaults are kicking in and we might want to muzzle them too ... https://github.com/makersacademy/instagram-challenge/pull/99

**Comment by tansaku** [comment]
some js muzzling: https://github.com/makersacademy/instagram-challenge/blob/master/.javascript-style.json

**Comment by silvabox** [comment]
Tested this with Ptolemy - there was a syntax error in rubocop.yml which we fixed.  There are a lot of errors being reported - 45 on the example repo we ran against

**Comment by tansaku** [comment]
discussed this with @silvabox - those offences were down from an original 150 - still room for improvement but going in the right direction - will need to check in with @ptolemybarnes @stephenlloyd and @sdorunga1 about how this went - early signs look slightly weird to me - I'm only seeing CSS issues from hound on the instagram-challenge, ah found a ruby one - okay - hmm - seeing something odd on the airport-challenge (hardly any hound issues) that makes me worry there's some systemic hound problem - investigating further ...
